import Foundation
class AddNewWords {
    //    let newWordsArray : [WordForLearning] = [
    //        WordForLearning(foreign: "הבית",
    //                        russian: "Дом",
    //                        isLearned: false,
    //                        levelOfLearning: 0,
    //                        nextContact: nil,
    //                        dontWantToLearn: false,
    //                        image: "home",
    //                        mistake: 0,
    //                        discription: nil,
    //                        simple: nil),
    //        WordForLearning(foreign: "רחוב",
    //                        russian: "Улица",
    //                        isLearned: false,
    //                        levelOfLearning: 0,
    //                        nextContact: nil,
    //                        dontWantToLearn: false,
    //                        image: "street",
    //                        mistake: 0,
    //                        discription: nil,
    //                        simple: nil),
    //        WordForLearning(foreign: "בחורה",
    //                        russian: "Девочка",
    //                        isLearned: false,
    //                        levelOfLearning: 0,
    //                        nextContact: nil,
    //                        dontWantToLearn: false,
    //                        image: "girl",
    //                        mistake: 0,
    //                        discription: nil,
    //                        simple: nil),
    //        WordForLearning(foreign: "אפל",
    //                        russian: "Яблоко",
    //                        isLearned: false,
    //                        levelOfLearning: 0,
    //                        nextContact: nil,
    //                        dontWantToLearn: false,
    //                        image: "apple",
    //                        mistake: 0,
    //                        discription: nil,
    //                        simple: nil),
    //        WordForLearning(foreign: "דגל",
    //                        russian: "Флаг",
    //                        isLearned: false,
    //                        levelOfLearning: 0,
    //                        nextContact: nil,
    //                        dontWantToLearn: false,
    //                        image: "flag",
    //                        mistake: 0,
    //                        discription: nil,
    //                        simple: nil),
    //    ]
    let newWordsArray : [WordForLearning] = [
        WordForLearning(foreign: "House",
                        original: "Дом",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "home",
                        mistake: 0,
                        discription: nil,
                        simple: nil),
        WordForLearning(foreign: "Street",
                        original: "Улица",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "street",
                        mistake: 0,
                        discription: nil,
                        simple: nil),
        WordForLearning(foreign: "Girl",
                        original: "Девочка",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "girl",
                        mistake: 0,
                        discription: nil,
                        simple: nil),
                WordForLearning(foreign: "Apple",
                                original: "Яблоко",
                                isLearned: false,
                                levelOfLearning: 0,
                                nextContact: nil,
                                dontWantToLearn: false,
                                image: "apple",
                                mistake: 0,
                                discription: nil,
                                simple: nil),
                WordForLearning(foreign: "Flag",
                                original: "Флаг",
                                isLearned: false,
                                levelOfLearning: 0,
                                nextContact: nil,
                                dontWantToLearn: false,
                                image: "flag",
                                mistake: 0,
                                discription: nil,
                                simple: nil),
    ]
}
