//
//  AddNewWords.swift
//  Learn Hebrew
//
//  Created by Anton Rubenchik on 18.08.2018.
//  Copyright © 2018 Anton Rubenchik. All rights reserved.
//

import Foundation
class AddNewWords {
    let newWordsArray : [WordForLearning] = []
//    let newWordsArray : [WordForLearning] = [
//        WordForLearning(foreign: "נַשְׂיא",
//                        original: "президент",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "president",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "наси"),
//        WordForLearning(foreign: "רוׂצֵחַ",
//                        original: "убийца",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "killer",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "роцеах"),
//        WordForLearning(foreign: "אֳנִיָה",
//                        original: "корабль",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "ship",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "онийа"),
//        WordForLearning(foreign: "סַכִּין",
//                        original: "нож",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "knife",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "сакин"),
//        WordForLearning(foreign: "בָּשָׂר",
//                        original: "мясо",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "meat",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "басар"),
//        WordForLearning(foreign: "צַלַחַת",
//                        original: "тарелка",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "plate",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "цалахат"),
//        WordForLearning(foreign: "יְרָקוֹת",
//                        original: "овощи",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "vegetable",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "йэракот"),
//        WordForLearning(foreign: "שָׂפָה",
//                        original: "язык (рус.анг.ивр)",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "language",
//                        mistake: 0,
//                        discription: nil,
//                        simple: "сафа"),
//        ]
}

/*
let newWordsArray : [WordForLearning] = [
    WordForLearning(foreign: "",
                    original: "",
                    isLearned: false,
                    levelOfLearning: 0,
                    nextContact: nil,
                    dontWantToLearn: false,
                    image: "",
                    mistake: 0,
                    discription: nil,
                    simple: ""),
]
 */
