//
//  AddNewWords.swift
//  Learn Hebrew
//
//  Created by Anton Rubenchik on 18.08.2018.
//  Copyright © 2018 Anton Rubenchik. All rights reserved.
//

import Foundation
class AddNewWords {
    let newWordsArray : [WordForLearning] = [
        WordForLearning(foreign: "אֶלֶף",
                        original: "тысяча",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "thousand",
                        mistake: 0,
                        discription: nil,
                        simple: "Э́леф"),
        WordForLearning(foreign: "אֶפֶס",
                        original: "ноль",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "zero",
                        mistake: 0,
                        discription: nil,
                        simple: "Э́фес"),
        WordForLearning(foreign: "שְׁלוֹשָׁה",
                        original: "три (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "three_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Шлоша́"),
        WordForLearning(foreign: "אַרְבַּעָה",
                        original: "четыре (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "four_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Арбаа́"),
        WordForLearning(foreign: "שָׁלוֹשׁ",
                        original: "три (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "three_w",
                        mistake: 0,
                        discription: nil,
                        simple: "Шало́ш"),
        WordForLearning(foreign: "אַרְבַּע",
                        original: "четыре (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "four_w",
                        mistake: 0,
                        discription: nil,
                        simple: "А́рба"),
        WordForLearning(foreign: "חָמִשָה",
                        original: "пять (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "five_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Хамиша́"),
        WordForLearning(foreign: "חָמֵשׁ",
                        original: "пять (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "five_w",
                        mistake: 0,
                        discription: nil,
                        simple: "Хамэ́ш"),
        WordForLearning(foreign: "שִׁשָהׁ",
                        original: "шесть (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "six_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Шиша́"),
        WordForLearning(foreign: "שֵש",
                        original: "шесть (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "six_w",
                        mistake: 0,
                        discription: nil,
                        simple: "шэш"),
        WordForLearning(foreign: "שִׁבַעָה",
                        original: "семь (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "seven_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Шив’а́"),
        WordForLearning(foreign: "שֶבַע",
                        original: "семь (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "seven_w",
                        mistake: 0,
                        discription: nil,
                        simple: "шэ́вас"),
        WordForLearning(foreign: "תִּשַׁעָה",
                        original: "девять (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "nine_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Тиш’а́"),
        WordForLearning(foreign: "תֵּשַע",
                        original: "девять (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "nine_w",
                        mistake: 0,
                        discription: nil,
                        simple: "Тэ́йша"),
        WordForLearning(foreign: "עֲשָׂרָה",
                        original: "десять (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "ten_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Асара́"),
        WordForLearning(foreign: "עֶשֶׂר",
                        original: "десять (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "ten_w",
                        mistake: 0,
                        discription: nil,
                        simple: "э́сэр"),
        WordForLearning(foreign: "אַחַד עָשָׂר",
                        original: "одиннадцать  (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "eleven_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Аха́д аса́р"),
        WordForLearning(foreign: "אַחַת עֵשׂרֶא",
                        original: "одиннадцать (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "eleven_w",
                        mistake: 0,
                        discription: nil,
                        simple: "Аха́т эсрэ́"),
        WordForLearning(foreign: "שנֵים עָשָׂר",
                        original: "двеннадцать  (М)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "twelve_m",
                        mistake: 0,
                        discription: nil,
                        simple: "Шнэ́йм аса́р"),
        WordForLearning(foreign: "שְׁתֵיים עֶשׂרֵא",
                        original: "двеннадцать (Ж)",
                        isLearned: false,
                        levelOfLearning: 0,
                        nextContact: nil,
                        dontWantToLearn: false,
                        image: "twelve_w",
                        mistake: 0,
                        discription: nil,
                        simple: "Штэ́йм эсрэ́"),

    ]
//    let newWordsArray : [WordForLearning] = [
//        WordForLearning(foreign: "House",
//                        original: "Дом",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "home",
//                        mistake: 0,
//                        discription: nil,
//                        simple: nil),
//        WordForLearning(foreign: "Street",
//                        original: "Улица",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "street",
//                        mistake: 0,
//                        discription: nil,
//                        simple: nil),
//        WordForLearning(foreign: "Girl",
//                        original: "Девочка",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "girl",
//                        mistake: 0,
//                        discription: nil,
//                        simple: nil),
//        WordForLearning(foreign: "Apple",
//                        original: "Яблоко",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "apple",
//                        mistake: 0,
//                        discription: nil,
//                        simple: nil),
//        WordForLearning(foreign: "Flag",
//                        original: "Флаг",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "flag",
//                        mistake: 0,
//                        discription: nil,
//                        simple: nil),
//        WordForLearning(foreign: "blue",
//                        original: "синий",
//                        isLearned: false,
//                        levelOfLearning: 0,
//                        nextContact: nil,
//                        dontWantToLearn: false,
//                        image: "blue",
//                        mistake: 0,
//                        discription: nil,
//                        simple: nil),
//        ]
}
